// <auto-generated />
namespace BorgioBase.Dominio1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TabelaMensalidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelaMensalidade));

        string IMigrationMetadata.Id
        {
            get { return "201504111343349_TabelaMensalidade"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
